# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yang-Hsien Lin 林仰賢
title: Ph.D.
email: d03945002@ntu.edu.tw
website: https://y-h-lin.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username: y-h-lin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: y-h-Lin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Yang-Hsien and I graduated with a PhD degree in biomedical electronics and bioinformatics from National Taiwan University in 2020. I have worked at China Medical University Hospital accerating radiomics and applying machine learning techniques on medical images.

  I am most skilled in: <mark>computer vision</mark>, <mark>radiology</mark>, <mark>biomedical optics and imaging</mark> and <mark>parallel computing with CUDA</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: China Medical University Hospital
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Big Data Engineer
        caption: Aug. 2017 - Aug. 2018
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Accerating the Radiomics to extract known features for machine learning. The deep learning techniques were also applied to delineate and detect lesions from medical images such as CT images and sonograms.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Taiwan University
        caption: 2014 - 2020
        sub_title: Biomedical Electronics and Bioinformatics
        description: | # this will include new lines to allow paragraphs
          Focus on optimizing the optics of digital holographic microscopy, tomographic diffractive microscopy, and accelerating the 2-D phase retrieval and 3-D refractive index tomogram reconstruction.

      - layout: left
        title: National Yang-Ming University
        caption: 2011 - 2013
        sub_title: Biomedical Imaging and Radiological Sciences
        description: | # this will include new lines to allow paragraphs
          Focus on estimating blood flow from digital subtraction angiography and quantifying cardiac wall motion on dynamic computed tomography.

  - title: Honors
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Graduate Student Outstanding Paper Award, National Taiwan University, 2017. 
      - The First Prize, GPU Acceleration of Phase Retrieval in Common-path Tomographic Diffractive Microscopy. NVIDIA GPU Technology Conference in Taiwan, Taipei, Taiwan, 2016. 
      - Research Excellence Award, National Yang Ming University, 2013.

  - title: Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Assisted Detection Model of Breast Tumor, and Assisted Detection System of Breast Tumor; Invention Patent No. TW201940124A; 2019/10/16.
      - Prediction Model for Grouping Hepatocellular Carcinoma, Prediction System Thereof, and Method for Determining Hepatocellular Carcinoma Group; Invention Patent No. TW201935403A; 2019/09/01.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Yang-Hsien Lin, Ken Ying-Kai Liao, Kung-Bin Sung*, "Automatic Detection and Characterization of Quantitative Phase Images of Thalassemic Red Blood Cells using Mask Region-based Convolutional Neural Network," Journal of Biomedical Optics. 2020; 25(11):116502.
      - Yang-Hsien Lin, Shin-Shyang Huang, Shang-Ju Wu, Kung-Bin Sung*, "Morphometric Analysis of Erythrocytes from Patients with Thalassemia using Tomographic Diffractive Microscopy," Journal of Biomedical Optics. 2017; 22(11):116009.
      - Jing-Wei Su, Yang-Hsien Lin, Chun-Ping Chiang, Jang-Ming Lee, Chao-Mao Hsieh, Min-Shu Hsieh, Pei-Wen Yang, Chen-Ping Wang, Ping-Huei Tseng, Yi-Chia Lee, and Kung-Bin Sung*, "Precancerous esophageal epithelia are associated with significantly increased scattering coefficients," Biomedical Optics Express. 2015; 6(10):3795-3805. 
      - Yang-Hsien Lin, Kang-Ping Lin, Shih-Min Huang, Hui-Ting Lu, Tien-Hsiang Lin, Tzung-Chi Huang*, "Left ventricle segmentation in dynamic cardiac CT using random walks method," Journal of X-ray science and technology. 2015; 23(1):25-31. 
      - Yang-Hsien Lin, Shih-Min Huang, Chin-Yi Huang, Yun-Niang Tu, Tzung-Chi Huang*, "Quantitative Analysis of Respiration-Related Movement for Abdominal Artery in Multiphase Hepatic CT," PloS one. 2014; 9(12):e114222. 
      - Yang-Hsien Lin, Kang-Ping Lin, Juhn-Cherng Liu, Tzung-Chi Huang*, "Ventricular hemodynamics using Cardiac Computed Tomography and Optical Flow Method," Journal of X-Ray Science and Technology. 2014;22(1):129-136. 
      - Tung-Hsin Wu, Chung-Jung Lin, Yang-Hsien Lin, Wan-Yuo Guo, Tzung-Chi Huang*, "Quantitative analysis of digital subtraction angiography using optical flow method on occlusive cerebrovascular disease," Computer Methods and Programs in Biomedicine. 2013;111(3):693-700. 
      - Tzung-Chi Huang, Tung-Hsin Wu, Yang-Hsien Lin, Wan-Yuo Guo, Wei-Chien Huang, Chung-Jung Lin*, "Quantitative Flow Measurement by Digital Subtraction Angiography in Cerebral Carotid Stenosis Using Optical Flow Method," Journal of X-Ray Science and Technology. 2013;21(2):227-235. 
      - Yao-Ching Wang, Hsun-Lin Tseng, Yang-Hsien Lin, Chia-Hung Kao, Wei-Chien Huang, Tzung-Chi Huang*, "Improvement of internal tumor volumes of non-small cell lung cancer patients for radiation treatment planning using interpolated average CT in PET/CT," PLoS One. 2013. 
      - Tzu-Ching Shih, Yang-Hsien Lin, Yung-Jen Ho, Hung-Da Hsiao, Yung-Hui Huang, Tzung-Chi Huang*, "Hemodynamic analysis of vascular stenting treatment outcome: Computational fluid dynamics method v.s. Optical flow method," Journal of X-Ray Science and Technology. 2012;20:469-481.  
      - Yung-Jen Ho, Mu-Bai Chang, Yang-Hsien Lin, Chun-Hsu Yao, Tzung-Chi Huang*, "Quantitative portal vein velocity of liver cancer patients with transcatheter arterial chemoembolization on angiography," The Scientific World Journal, 2012. 
      - Wen-Chen Lin, Chih-Chieh Wu, Geoffrey Zhang, Tung-Hsin Wu, Yang-Hsien Lin, Tzung-Chi Huang*, Ren-Shyan Liu, Kang-Ping Lin, "An Approach to Automatic Blood Vessel Image Registration of Microcirculation for Blood Flow Analysis on Nude Mice," Computer Methods in Biomechanics and Biomedical Engineering. 2011;14(4):319-330. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
